### PR TITLE
Make parallel requests to fetch checkin data

### LINKED ISSUE #15: makeFetchCheckinDataAttempts is taking more than 250 ms between request
Hey,

One thing that I'd like in an automated checkin is knowing that it is faster than me as a human. I notice that in the logs for successful checkins, we are retrying about every 1200 ms instead of 250 ms. 

I assume the method will wait for a response each time, before retrying. 

This may cause the checkin to be slightly slower than a human (I'll be testing this soon! Have a flight coming up with friends and I'll see who gets the better seat!)

I don't really understand how this function works, but is there anyway we can improve it to **actually** retry every 250ms?

Logs below for a checkin, with the timestamps.

```
2022-02-08T09:54:55.103-08:00	2022-02-08T17:54:55.103Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Starting fetch checkin data attempts at February 8, 2022, 5:54:55 PM UTC

2022-02-08T09:54:56.335-08:00	2022-02-08T17:54:56.335Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 1 of 79 at February 8, 2022, 5:54:56 PM UTC with error: {"code":400308191,"message":"Sorry! This reservation is not eligible for check in.","messageKey":"ERROR__AIR_TRAVEL__BEFORE_CHECKIN_WINDOW","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:HLNvijr2Rd-J0_jN4wYfdQ:mweb","infoList":[]}

2022-02-08T09:54:57.489-08:00	2022-02-08T17:54:57.489Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 2 of 79 at February 8, 2022, 5:54:57 PM UTC with error: {"code":400308191,"message":"Sorry! This reservation is not eligible for check in.","messageKey":"ERROR__AIR_TRAVEL__BEFORE_CHECKIN_WINDOW","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:igJRoWOAR9mhm5IPopOfRw:mweb","infoList":[]}

2022-02-08T09:54:58.986-08:00	2022-02-08T17:54:58.986Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 3 of 79 at February 8, 2022, 5:54:58 PM UTC with error: {"code":400308191,"message":"Sorry! This reservation is not eligible for check in.","messageKey":"ERROR__AIR_TRAVEL__BEFORE_CHECKIN_WINDOW","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:W8DxRxxsR0-aK4rffe16sg:mweb","infoList":[]}

2022-02-08T09:55:00.183-08:00	2022-02-08T17:55:00.183Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 4 of 79 at February 8, 2022, 5:55:00 PM UTC with error: {"code":400308192,"message":"This flight is currently not ready for check-in. Please try again momentarily.","messageKey":"ERROR__AIR_TRAVEL__NOT_OPEN","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:OhvnWYMKSPaG8oYA3_XfpQ:mweb","infoList":[]}

2022-02-08T09:55:01.341-08:00	2022-02-08T17:55:01.341Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 5 of 79 at February 8, 2022, 5:55:01 PM UTC with error: {"code":400308192,"message":"This flight is currently not ready for check-in. Please try again momentarily.","messageKey":"ERROR__AIR_TRAVEL__NOT_OPEN","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:8yIM279MSZeivl6jx-2UdA:mweb","infoList":[]}

2022-02-08T09:55:02.634-08:00	2022-02-08T17:55:02.633Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 6 of 79 at February 8, 2022, 5:55:02 PM UTC with error: {"code":400308192,"message":"This flight is currently not ready for check-in. Please try again momentarily.","messageKey":"ERROR__AIR_TRAVEL__NOT_OPEN","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:r73KbXEeRVqib9ZWKsTj8Q:mweb","infoList":[]}

2022-02-08T09:55:03.877-08:00	2022-02-08T17:55:03.876Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 7 of 79 at February 8, 2022, 5:55:03 PM UTC with error: {"code":400308192,"message":"This flight is currently not ready for check-in. Please try again momentarily.","messageKey":"ERROR__AIR_TRAVEL__NOT_OPEN","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:o0w862NyQ3msfktAcawv9Q:mweb","infoList":[]}

2022-02-08T09:55:05.209-08:00	2022-02-08T17:55:05.209Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Failed on attempt 8 of 79 at February 8, 2022, 5:55:05 PM UTC with error: {"code":400308192,"message":"This flight is currently not ready for check-in. Please try again momentarily.","messageKey":"ERROR__AIR_TRAVEL__NOT_OPEN","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"9FC88DE0-8907-11EC-BE80-6DDA96DCCD60:hHu9X5xoTQ6CeL-wLvnrPg:mweb","infoList":[]}

2022-02-08T09:55:06.904-08:00	2022-02-08T17:55:06.903Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Checking in at February 8, 2022, 5:55:06 PM UTC

2022-02-08T09:55:08.991-08:00	2022-02-08T17:55:08.991Z e7ae96a5-bab7-43ad-9eda-489fa7faee43 INFO Checkin succeeded
```

### PR DESCRIPTION
**Pull request by swtools0**
Resolves #15

### CODE REVIEW

File: src/lib/check-in.ts [hunk 1]
```diff
@@ -1,14 +1,85 @@
...
+  // Create a cancel function that can be used to cancel the attempts. We are essentially
+  // implementing a cancelable promise. We use this to cancel the remaining attempts once we get one
+  // successful response.
+
+  const signal = createCancellableSignal();
+
+  // schedule requests such that they are made on each `input.millisPerRequest` interval
+
+  const promises = [];
+  for (let attempt = 0; attempt < input.attemptLimit; attempt++) {
```
Comment (aaron-pham) [inline src/lib/check-in.ts:30]: This is pretty clever! I'm still getting familiar with node/javascript concepts, but is this what you're essentially doing?

Creating 80 requests with a delay on when to actually execute (so the first one waits 0 seconds, next 0.25, next 0.5), once you get a successful response from any of them, cancel all request that are still waiting for their time.

What I'm a little confused on, how does this piece work? `const response = await Promise.any(promises);`

More specifically, even in the case of a "failed" request (in `makeDelayedRequest`), we'll catch and log the error, but then we'll still return `response` which would be empty since the request failed. This would trigger our `const response = await Promise.any(promises);` to trigger and we'll cancel all the rest of the request we make.

Or am I misunderstanding something?

File: src/lib/check-in.ts [hunk 2]
```diff
@@ -18,45 +89,35 @@ export function makeFetchCheckinDataAttempts(
...
+        input.attempt,
+        input.attemptLimit,
+        nowTimestamp,
+        error
+      );
     }
-  });
+  }
+
+  return response;
```
Comment (aaron-pham) [inline src/lib/check-in.ts:120]: See here, if we're making a bunch of individual request with the promises to delay when they actually run, we'll still return response regardless if it was a success or failed request... right?

Comment (swtools0) [reply src/lib/check-in.ts:122]: Great catch, I've updated the catch block to re-throw the error

File: src/lib/check-in.ts (hunk 1 above)
Comment (swtools0) [reply src/lib/check-in.ts:30]: You are exactly correct

**Comment by aaron-pham** [comment]
Hey, I recently just deployed this branch to my aws account and was doing some testing. I am getting an error `ERROR	TypeError: Promise.any is not a function`. It appears that Promise.any is a node.js 15+ thing, while the lambda runtime is 14.x . I'm still looking into this but just a heads up.

File: src/lib/check-in.ts [hunk 3]
```diff
@@ -18,45 +89,37 @@ export function makeFetchCheckinDataAttempts(
...
+      );
+      // It's normal to see many of these messages before we get the good response. We try
+      // many times because the airline's API has a quirk of not making checkin available at
+      // exactly the time expected.
+      input.logger.log(
+        'Failed to fetch checkin data on attempt %d of %d at %s with error:',
+        input.attempt,
+        input.attemptLimit,
+        nowTimestamp,
+        error
```
Comment (aaron-pham) [inline src/lib/check-in.ts:115]: It'll be nice to keep the logging the same as before so we log the response body (which has all the error info as well).

**Comment by aaron-pham** [comment]
Okay, I found a workaround for the issue above - https://www.npmjs.com/package/promise.any, this library is a Promise.any() replacement I believe.

However, I tried doing a checkin with this code + arn addition + that promise.any replacement, and the checkin ended up failing. Not sure what happened but all 80 of my request for a 404 not found. The flight was definitely ready for checkin.

I'll be putting this down for the night, but let me know if you have any additional findings!

File: src/lib/check-in.ts (hunk 3 above)
Comment (swtools0) [reply src/lib/check-in.ts]: Thanks for testing this PR! I've updated this to log out `util.inspect(error)`. I'm not sure what the structure of this error looks like, but this should just print everything. If you still have a flight ready for checkin, maybe you can try to check in with this change and see if the full error yields any more information about why we're getting 404 responses.

File: src/lib/check-in.ts [hunk 4]
```diff
@@ -18,45 +92,37 @@ export function makeFetchCheckinDataAttempts(
...
-      'mobile-air-operations/v1/mobile-air-operations/page/check-in/',
-      reservation
-    ),
-    method: SwClient.Method.GET,
-    headers,
-    retry: {
-      // We'll try a total of 80 times.
-      // This should give us 5 seconds of checkin tries before checkin time and 15 seconds after.
-      limit: 79,
-      methods: [SwClient.Method.POST],
```
Comment (aaron-pham) [inline src/lib/check-in.ts:32]: Should there be a POST for the other "new" way? Maybe not, as it seems like the checkin happens in two steps. First get the data on `'mobile-air-operations/v1/mobile-air-operations/page/check-in/'`, then post to another url to complete the checkin.

File: src/lib/check-in.ts (hunk 3 above)
Comment (aaron-pham) [reply src/lib/check-in.ts]: I'll book a flight today to test it :P. I have another flight upcoming this saturday that's I'll actually be going on, so hoping to test if it'll beat humans haha.

File: src/lib/check-in.ts (hunk 4 above)
Comment (swtools0) [reply src/lib/check-in.ts:32]: Yeah I was looking at that too, but I think this`methods: [SwClient.Method.POST]` line was unnecessary before.

We were issuing a GET request in this function before and we're still issuing a GET request.

File: src/lib/check-in.ts (hunk 3 above)
Comment (swtools0) [reply src/lib/check-in.ts]: I made another change, make sure you pull again

**Comment by aaron-pham** [comment]
I've confirmed this works, the logging didn't change though (before you added depth).

**Comment by swtools0** [comment]
> I've confirmed this works (after rebasing on master of course), the logging didn't change though (before you added depth).

It successfully checked you in or you can see the full error now?

**Comment by aaron-pham** [comment]
Oops sorry, it successfully checked me in. The logs appeared the same (not showing the entire block) but I had `util.inspect(error)` on my version. Didn't pick up the change to `util.inspect(error, { depth: null })` by the time my checkin was ready.
